plugins {
    id 'com.android.application'
    id('dev.rikka.tools.refine') version '4.3.0'
}

def localProperties = new Properties()
if (rootProject.file("local.properties").canRead()) {
    localProperties.load(rootProject.file("local.properties").newDataInputStream())
}
def hasReleaseKeystore = localProperties.getProperty("androidStoreFile") != null

android {
    compileSdk 36

    defaultConfig {
        applicationId "de.yisrime.dimming"
        minSdk 31
        targetSdk 33
        versionCode 110
        versionName "1.1.0"

    }
    applicationVariants.all { variant ->
        variant.resValue "string", "app_version_name", variant.versionName
    }
    signingConfigs {
        if (hasReleaseKeystore) {
            config {
                storeFile file(localProperties.getProperty("androidStoreFile"))
                storePassword localProperties.getProperty("androidStorePassword")
                keyAlias localProperties.getProperty("androidKeyAlias")
                keyPassword localProperties.getProperty("androidKeyPassword")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (hasReleaseKeystore) {
                signingConfig signingConfigs.config
            }
        }
    }
    buildFeatures {
        aidl true
    }
    compileOptions {
        //coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    namespace 'de.yisrime.dimming'
}

dependencies {
    implementation 'net.jcip:jcip-annotations:1.0'
    compileOnly('androidx.annotation:annotation-jvm:1.6.0')
    compileOnly project(path: ':hidden-api')
    compileOnly("io.github.libxposed:api:101.0.1")
    implementation("io.github.libxposed:service:101.0.0")
    // coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'
}